drop table pokedex_kanto;

CREATE TABLE pokedex_kanto(
    index INT,
    pokemon VARCHAR(10),
    type1 VARCHAR(10),
    type2 VARCHAR(10)
);
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (1  , 'Bulbasaur'  , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (2  , 'Ivysaur'    , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (3  , 'Venusaur'   , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (4  , 'Charmander' , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (5  , 'Charmeleon' , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (6  , 'Charizard'  , 'Fire'    , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (7  , 'Squirtle'   , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (8  , 'Wartortle'  , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (9  , 'Blastoise'  , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (10 , 'Caterpie'   , 'Bug'     , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (11 , 'Metapod'    , 'Bug'     , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (12 , 'Butterfree' , 'Bug'     , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (13 , 'Weedle'     , 'Bug'     , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (14 , 'Kakuna'     , 'Bug'     , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (15 , 'Beedrill'   , 'Bug'     , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (16 , 'Pidgey'     , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (17 , 'Pidgeotto'  , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (18 , 'Pidgeot'    , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (19 , 'Rattata'    , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (20 , 'Raticate'   , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (21 , 'Spearow'    , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (22 , 'Fearow'     , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (23 , 'Ekans'      , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (24 , 'Arbok'      , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (25 , 'Pikachu'    , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (26 , 'Raichu'     , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (27 , 'Sandshrew'  , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (28 , 'Sandslash'  , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (29 , 'Nidoran♀'   , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (30 , 'Nidorina'   , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (31 , 'Nidoqueen'  , 'Poison'  , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (32 , 'Nidoran♂'   , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (33 , 'Nidorino'   , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (34 , 'Nidoking'   , 'Poison'  , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (35 , 'Clefairy'   , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (36 , 'Clefable'   , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (37 , 'Vulpix'     , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (38 , 'Ninetales'  , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (39 , 'Jigglypuff' , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (40 , 'Wigglytuff' , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (41 , 'Zubat'      , 'Poison'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (42 , 'Golbat'     , 'Poison'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (43 , 'Oddish'     , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (44 , 'Gloom'      , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (45 , 'Vineplume'  , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (46 , 'Paras'      , 'Bug'     , 'Grass'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (47 , 'Parasect'   , 'Bug'     , 'Grass'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (48 , 'Venonat'    , 'Bug'     , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (49 , 'Venomoth'   , 'Bug'     , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (50 , 'Diglett'    , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (51 , 'Dugtrio'    , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (52 , 'Meowth'     , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (53 , 'Persian'    , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (54 , 'Psyduck'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (55 , 'Golduck'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (56 , 'Mankey'     , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (57 , 'Primeape'   , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (58 , 'Growlithe'  , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (59 , 'Arcanine'   , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (60 , 'Poliwag'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (61 , 'Poliwhirl'  , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (62 , 'Poliwrath'  , 'Water'   , 'Fighting');
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (63 , 'Abra'       , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (64 , 'Kadabra'    , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (65 , 'Alakazam'   , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (66 , 'Machop'     , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (67 , 'Machoke'    , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (68 , 'Machamp'    , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (69 , 'Bellsprout' , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (70 , 'Weepinbell' , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (71 , 'Victreebel' , 'Grass'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (72 , 'Tentacool'  , 'Water'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (73 , 'Tentacruel' , 'Water'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (74 , 'Geodude'    , 'Rock'    , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (75 , 'Graveler'   , 'Rock'    , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (76 , 'Golem'      , 'Rock'    , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (77 , 'Ponyta'     , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (78 , 'Rapidash'   , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (79 , 'Slowpoke'   , 'Water'   , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (80 , 'Slowbro'    , 'Water'   , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (81 , 'Magnemite'  , 'Electric', 'Steel'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (82 , 'Magneton'   , 'Electric', 'Steel'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (83 , 'Farfetch''d', 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (84 , 'Doduo'      , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (85 , 'Dodrio'     , 'Normal'  , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (86 , 'Seel'       , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (87 , 'Dewgong'    , 'Water'   , 'Ice'     );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (88 , 'Grimer'     , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (89 , 'Muk'        , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (90 , 'Shellder'   , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (91 , 'Cloyster'   , 'Water'   , 'Ice'     );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (92 , 'Ghastly'    , 'Ghost'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (93 , 'Haunter'    , 'Ghost'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (94 , 'Gengar'     , 'Ghost'   , 'Poison'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (95 , 'Onix'       , 'Rock'    , 'Ground'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (96 , 'Drowzee'    , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (97 , 'Hypno'      , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (98 , 'Krabby'     , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (99 , 'Kingler'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (100, 'Voltorb'    , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (101, 'Electrode'  , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (102, 'Exeggcute'  , 'Grass'   , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (103, 'Exeggutor'  , 'Grass'   , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (104, 'Cubone'     , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (105, 'Marowak'    , 'Ground'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (106, 'Hitmonlee'  , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (107, 'Hitmonchan' , 'Fighting', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (108, 'Lickitung'  , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (109, 'Koffing'    , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (110, 'Weezing'    , 'Poison'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (111, 'Rhyhorn'    , 'Ground'  , 'Rock'    );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (112, 'Rhydon'     , 'Ground'  , 'Rock'    );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (113, 'Chansey'    , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (114, 'Tangela'    , 'Grass'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (115, 'Kangaskhan' , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (116, 'Horsea'     , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (117, 'Seadra'     , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (118, 'Goldeen'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (119, 'Seaking'    , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (120, 'Staryu'     , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (121, 'Starmine'   , 'Water'   , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (122, 'Mr. Mime'   , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (123, 'Scyther'    , 'Bug'     , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (124, 'Jynx'       , 'Ice'     , 'Psychic' );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (125, 'Electabuzz' , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (126, 'Magmar'     , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (127, 'Pinsir'     , 'Bug'     , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (128, 'Tauros'     , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (129, 'Magikarp'   , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (130, 'Gyarados'   , 'Water'   , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (131, 'Lapras'     , 'Water'   , 'Ice'     );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (132, 'Ditto'      , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (133, 'Eevee'      , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (134, 'Vaporeon'   , 'Water'   , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (135, 'Jolteon'    , 'Electric', NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (136, 'Flareon'    , 'Fire'    , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (137, 'Porygon'    , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (138, 'Omanyte'    , 'Rock'    , 'Water'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (139, 'Omastar'    , 'Rock'    , 'Water'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (140, 'Kabuto'     , 'Rock'    , 'Water'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (141, 'Kabutops'   , 'Rock'    , 'Water'   );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (142, 'Aerodactyl' , 'Rock'    , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (143, 'Snorlax'    , 'Normal'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (144, 'Articuno'   , 'Ice'     , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (145, 'Zapdos'     , 'Electric', 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (146, 'Moltres'    , 'Fire'    , 'Flying'  );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (147, 'Dratini'    , 'Dragon'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (148, 'Dragonair'  , 'Dragon'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (149, 'Dragonite'  , 'Dragon'  , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (150, 'Mewtwo'     , 'Psychic' , NULL      );
INSERT INTO pokedex_kanto (index, pokemon, type1, type2) VALUES (151, 'Mew'        , 'Psychic' , NULl      );