DROP TABLE pokedex_kanto;
DROP TABLE movedex_gen3;
DROP TABLE squirtle_moves;
DROP TABLE charmander_moves;

CREATE TABLE pokedex_kanto(
    NO INT,
    pokemon VARCHAR(10),
    type1 VARCHAR(10),
    type2 VARCHAR(10),
    classification VARCHAR(20),
    category VARCHAR(20),
    ability VARCHAR(20),
    male FLOAT,
    female FLOAT,
    height FLOAT,
    weight FLOAT
);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (1  , 'Bulbasaur'  , 'Grass'   , 'Poison'  , 'Seed'       , 'Grassland'    , 'Overgrow'     , 87.5, 12.5, 0.7, 6.9);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (2  , 'Ivysaur'    , 'Grass'   , 'Poison'  , 'Seed'       , 'Grassland'    , 'Overgrow'     , 87.5, 12.5, 1.0, 13.0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (3  , 'Venusaur'   , 'Grass'   , 'Poison'  , 'Seed'       , 'Grassland'    , 'Overgrow'     , 87.5, 12.5, 2.0, 100.0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (4  , 'Charmander' , 'Fire'    , NULL      , 'Lizard'     , 'Mountain'     , 'Blaze'        , 87.5, 12.5, 0.6, 8.5);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (5  , 'Charmeleon' , 'Fire'    , NULL      , 'Flame'      , 'Mountain'     , 'Blaze'        , 87.5, 12.5, 1.9, 19.0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (6  , 'Charizard'  , 'Fire'    , 'Flying'  , 'Flame'      , 'Mountain'     , 'Blaze'        , 87.5, 12.5, 1.7, 90.5);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (7  , 'Squirtle'   , 'Water'   , NULL      , 'Tiny Turtle', 'Water''s-edge', 'Torrent'      , 87.5, 12.5, 0.5, 9.0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (8  , 'Wartortle'  , 'Water'   , NULL      , 'Turtle'     , 'Water''s-edge', 'Torrent'      , 87.5, 12.5, 1.0, 22.5);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (9  , 'Blastoise'  , 'Water'   , NULL      , 'Shellfish'  , 'Water''s-edge', 'Torrent'      , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (10 , 'Caterpie'   , 'Bug'     , NULL      , 'Worm'       , 'Forest'       , 'Shield Dust'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (11 , 'Metapod'    , 'Bug'     , NULL      , 'Cocoon'     , 'Forest'       , 'Shed Skin'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (12 , 'Butterfree' , 'Bug'     , 'Flying'  , 'Butterfly'  , 'Forest'       , 'Compound Eyes', 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (13 , 'Weedle'     , 'Bug'     , 'Poison'  , 'Hairy Bug'  , 'Forest'       , 'Shield Dust'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (14 , 'Kakuna'     , 'Bug'     , 'Poison'  , 'Cocoon'     , 'Forest'       , 'Shed Skin'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (15 , 'Beedrill'   , 'Bug'     , 'Poison'  , 'Poison Bee' , 'Forest'       , 'Swarm'        , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (16 , 'Pidgey'     , 'Normal'  , 'Flying'  , 'Tiny Bird'  , 'Forest'       , 'Keen Eye'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (17 , 'Pidgeotto'  , 'Normal'  , 'Flying'  , 'Bird'       , 'Forest'       , 'Keen Eye'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (18 , 'Pidgeot'    , 'Normal'  , 'Flying'  , 'Bird'       , 'Forest'       , 'Keen Eye'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (19 , 'Rattata'    , 'Normal'  , NULL      , 'Mouse'      , 'Grassland'    , 'Guts'         , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (20 , 'Raticate'   , 'Normal'  , NULL      , 'Mouse'      , 'Grassland'    , 'Guts'         , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (21 , 'Spearow'    , 'Normal'  , 'Flying'  , 'Tiny Bird'  , 'Rough-terrain', 'Keen Eye'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (22 , 'Fearow'     , 'Normal'  , 'Flying'  , 'Beak'       , 'Rough-terrain', 'Keen Eye'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (23 , 'Ekans'      , 'Poison'  , NULL      , 'Snake'      , 'Grassland'    , 'Intimidate'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (24 , 'Arbok'      , 'Poison'  , NULL      , 'Cobra'      , 'Grassland'    , 'Intimidate'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (25 , 'Pikachu'    , 'Electric', NULL      , 'Mouse'      , 'Forest'       , 'Static'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (26 , 'Raichu'     , 'Electric', NULL      , 'Mouse'      , 'Forest'       , 'Static'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (27 , 'Sandshrew'  , 'Ground'  , NULL      , 'Mouse'      , 'Rough-terrain', 'Sand Veil'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (28 , 'Sandslash'  , 'Ground'  , NULL      , 'Mouse'      , 'Rough-terrain', 'Sand Veil'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (29 , 'Nidoran♀'   , 'Poison'  , NULL      , 'Poison Pin' , 'Grassland'    , 'Poison Point' , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (30 , 'Nidorina'   , 'Poison'  , NULL      , 'Poison Pin' , 'Grassland'    , 'Poison Point' , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (31 , 'Nidoqueen'  , 'Poison'  , 'Ground'  , 'Drill'      , 'Grassland'    , 'Poison Point' , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (32 , 'Nidoran♂'   , 'Poison'  , NULL      , 'Poison Pin' , 'Grassland'    , 'Poison Point' , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (33 , 'Nidorino'   , 'Poison'  , NULL      , 'Poison Pin' , 'Grassland'    , 'Poison Point' , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (34 , 'Nidoking'   , 'Poison'  , 'Ground'  , 'Drill'      , 'Grassland'    , 'Poison Point' , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (35 , 'Clefairy'   , 'Normal'  , NULL      , 'Fairy'      , 'Mountain'     , 'Cute Charm'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (36 , 'Clefable'   , 'Normal'  , NULL      , 'Fairy'      , 'Mountain'     , 'Cute Charm'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (37 , 'Vulpix'     , 'Fire'    , NULL      , 'Fox'        , 'Grassland'    , 'Flash Fire'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (38 , 'Ninetales'  , 'Fire'    , NULL      , 'Fox'        , 'Grassland'    , 'Flash Fire'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (39 , 'Jigglypuff' , 'Normal'  , NULL      , 'Balloon'    , 'Grassland'    , 'Cute Charm'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (40 , 'Wigglytuff' , 'Normal'  , NULL      , 'Balloon'    , 'Grassland'    , 'Cute Charm'   , 25.0, 75.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (41 , 'Zubat'      , 'Poison'  , 'Flying'  , 'Bat'        , 'Cave'         , 'Inner Focus'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (42 , 'Golbat'     , 'Poison'  , 'Flying'  , 'Bat'        , 'Cave'         , 'Inner Focus'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (43 , 'Oddish'     , 'Grass'   , 'Poison'  , 'Weed'       , 'Grassland'    , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (44 , 'Gloom'      , 'Grass'   , 'Poison'  , 'Weed'       , 'Grassland'    , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (45 , 'Vineplume'  , 'Grass'   , 'Poison'  , 'Flower'     , 'Grassland'    , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (46 , 'Paras'      , 'Bug'     , 'Grass'   , 'Mushroom'   , 'Forest'       , 'Effect Spore' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (47 , 'Parasect'   , 'Bug'     , 'Grass'   , 'Mushroom'   , 'Forest'       , 'Effect Spore' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (48 , 'Venonat'    , 'Bug'     , 'Poison'  , 'Insect'     , 'Forest'       , 'Compound Eyes', 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (49 , 'Venomoth'   , 'Bug'     , 'Poison'  , 'Poison Moth', 'Forest'       , 'Shield Dust'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (50 , 'Diglett'    , 'Ground'  , NULL      , 'Mole'       , 'Cave'         , 'Arena Trap'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (51 , 'Dugtrio'    , 'Ground'  , NULL      , 'Mole'       , 'Cave'         , 'Arena Trap'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (52 , 'Meowth'     , 'Normal'  , NULL      , 'Scratch Cat', 'Urban'        , 'Pickup'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (53 , 'Persian'    , 'Normal'  , NULL      , 'Classy Cat' , 'Urban'        , 'Limber'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (54 , 'Psyduck'    , 'Water'   , NULL      , 'Duck'       , 'Water''s-edge', 'Damp'         , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (55 , 'Golduck'    , 'Water'   , NULL      , 'Duck'       , 'Water''s-edge', 'Cloud Nine'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (56 , 'Mankey'     , 'Fighting', NULL      , 'Pig Monkey' , 'Mountain'     , 'Vital Spirit' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (57 , 'Primeape'   , 'Fighting', NULL      , 'Pig Monkey' , 'Mountain'     , 'Vital Spirit' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (58 , 'Growlithe'  , 'Fire'    , NULL      , 'Puppy'      , 'Grassland'    , 'Intimidate'   , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (59 , 'Arcanine'   , 'Fire'    , NULL      , 'Legendary'  , 'Grassland'    , 'Intimidate'   , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (60 , 'Poliwag'    , 'Water'   , NULL      , 'Tadpole'    , 'Water''s-edge', 'Water Absorb' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (61 , 'Poliwhirl'  , 'Water'   , NULL      , 'Tadpole'    , 'Water''s-edge', 'Water Absorb' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (62 , 'Poliwrath'  , 'Water'   , 'Fighting', 'Tadpole'    , 'Water''s-edge', 'Water Absorb' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (63 , 'Abra'       , 'Psychic' , NULL      , 'Psi'        , 'Urban'        , 'Synchronize'  , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (64 , 'Kadabra'    , 'Psychic' , NULL      , 'Psi'        , 'Urban'        , 'Synchronize'  , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (65 , 'Alakazam'   , 'Psychic' , NULL      , 'Psi'        , 'Urban'        , 'Synchronize'  , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (66 , 'Machop'     , 'Fighting', NULL      , 'Superpower' , 'Mountain'     , 'Guts'         , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (67 , 'Machoke'    , 'Fighting', NULL      , 'Superpower' , 'Mountain'     , 'Guts'         , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (68 , 'Machamp'    , 'Fighting', NULL      , 'Superpower' , 'Mountain'     , 'Guts'         , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (69 , 'Bellsprout' , 'Grass'   , 'Poison'  , 'Flower'     , 'Forest'       , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (70 , 'Weepinbell' , 'Grass'   , 'Poison'  , 'Flycatcher' , 'Forest'       , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (71 , 'Victreebel' , 'Grass'   , 'Poison'  , 'Flycatcher' , 'Forest'       , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (72 , 'Tentacool'  , 'Water'   , 'Poison'  , 'Jellyfish'  , 'Sea'          , 'Liquid Ooze'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (73 , 'Tentacruel' , 'Water'   , 'Poison'  , 'Jellyfish'  , 'Sea'          , 'Clear Body'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (74 , 'Geodude'    , 'Rock'    , 'Ground'  , 'Rock'       , 'Mountain'     , 'Rock Head'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (75 , 'Graveler'   , 'Rock'    , 'Ground'  , 'Rock'       , 'Mountain'     , 'Sturdy'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (76 , 'Golem'      , 'Rock'    , 'Ground'  , 'Megaton'    , 'Mountain'     , 'Sturdy'       , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (77 , 'Ponyta'     , 'Fire'    , NULL      , 'Fire Horse' , 'Grassland'    , 'Flash Fire'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (78 , 'Rapidash'   , 'Fire'    , NULL      , 'Fire Horse' , 'Grassland'    , 'Flash Fire'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (79 , 'Slowpoke'   , 'Water'   , 'Psychic' , 'Dopey'      , 'Water''s-edge', 'Own Tempo'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (80 , 'Slowbro'    , 'Water'   , 'Psychic' , 'Hermit Crab', 'Water''s-edge', 'Own Tempo'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (81 , 'Magnemite'  , 'Electric', 'Steel'   , 'Magnet'     , 'Rough-terrain', 'Magnet Pull'  , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (82 , 'Magneton'   , 'Electric', 'Steel'   , 'Magnet'     , 'Rough-terrain', 'Magnet Pull'  , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (83 , 'Farfetch''d', 'Normal'  , 'Flying'  , 'Wild Duck'  , 'Grassland'    , 'Inner Focus'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (84 , 'Doduo'      , 'Normal'  , 'Flying'  , 'Twin Bird'  , 'Grassland'    , 'Early Bird'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (85 , 'Dodrio'     , 'Normal'  , 'Flying'  , 'Triple Bird', 'Grassland'    , 'Early Bird'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (86 , 'Seel'       , 'Water'   , NULL      , 'Sea Lion'   , 'Sea'          , 'Thick Fat'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (87 , 'Dewgong'    , 'Water'   , 'Ice'     , 'Sea Lion'   , 'Sea'          , 'Thick Fat'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (88 , 'Grimer'     , 'Poison'  , NULL      , 'Sludge'     , 'Urban'        , 'Sticky Hold'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (89 , 'Muk'        , 'Poison'  , NULL      , 'Sludge'     , 'Urban'        , 'Sticky Hold'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (90 , 'Shellder'   , 'Water'   , NULL      , 'Bivalve'    , 'Sea'          , 'Shell Armor'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (91 , 'Cloyster'   , 'Water'   , 'Ice'     , 'Bivalve'    , 'Sea'          , 'Shell Armor'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (92 , 'Ghastly'    , 'Ghost'   , 'Poison'  , 'Gas'        , 'Cave'         , 'Levitate'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (93 , 'Haunter'    , 'Ghost'   , 'Poison'  , 'Gas'        , 'Cave'         , 'Levitate'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (94 , 'Gengar'     , 'Ghost'   , 'Poison'  , 'Shadow'     , 'Cave'         , 'Levitate'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (95 , 'Onix'       , 'Rock'    , 'Ground'  , 'Rock Snake' , 'Cave'         , 'Rock Head'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (96 , 'Drowzee'    , 'Psychic' , NULL      , 'Hypnosis'   , 'Grassland'    , 'Insomnia'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (97 , 'Hypno'      , 'Psychic' , NULL      , 'Hypnosis'   , 'Grassland'    , 'Insomnia'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (98 , 'Krabby'     , 'Water'   , NULL      , 'River Crab' , 'Water''s-edge', 'Shell Armor'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (99 , 'Kingler'    , 'Water'   , NULL      , 'Pincer'     , 'Water''s-edge', 'Hyper Cutter' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (100, 'Voltorb'    , 'Electric', NULL      , 'Ball'       , 'Urban'        , 'Soundproof'   , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (101, 'Electrode'  , 'Electric', NULL      , 'Ball'       , 'Urban'        , 'Static'       , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (102, 'Exeggcute'  , 'Grass'   , 'Psychic' , 'Egg'        , 'Forest'       , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (103, 'Exeggutor'  , 'Grass'   , 'Psychic' , 'Coconut'    , 'Forest'       , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (104, 'Cubone'     , 'Ground'  , NULL      , 'Lonely'     , 'Mountain'     , 'Rock Head'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (105, 'Marowak'    , 'Ground'  , NULL      , 'Bone Keeper', 'Mountain'     , 'Rock Head'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (106, 'Hitmonlee'  , 'Fighting', NULL      , 'Kicking'    , 'Urban'        , 'Limber'       , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (107, 'Hitmonchan' , 'Fighting', NULL      , 'Punching'   , 'Urban'        , 'Keen Eye'     , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (108, 'Lickitung'  , 'Normal'  , NULL      , 'Licking'    , 'Grassland'    , 'Own Tempo'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (109, 'Koffing'    , 'Poison'  , NULL      , 'Poison Gas' , 'Urban'        , 'Levitate'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (110, 'Weezing'    , 'Poison'  , NULL      , 'Poison Gas' , 'Urban'        , 'Levitate'     , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (111, 'Rhyhorn'    , 'Ground'  , 'Rock'    , 'Spikes'     , 'Rough-terrain', 'Lightning Rod', 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (112, 'Rhydon'     , 'Ground'  , 'Rock'    , 'Drill'      , 'Rough-terrain', 'Rock Head'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (113, 'Chansey'    , 'Normal'  , NULL      , 'Egg'        , 'Urban'        , 'Natural Cure' , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (114, 'Tangela'    , 'Grass'   , NULL      , 'Vine'       , 'Grassland'    , 'Chlorophyll'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (115, 'Kangaskhan' , 'Normal'  , NULL      , 'Parent'     , 'Grassland'    , 'Early Bird'   , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (116, 'Horsea'     , 'Water'   , NULL      , 'Dragon'     , 'Sea'          , 'Swift Spin'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (117, 'Seadra'     , 'Water'   , NULL      , 'Dragon'     , 'Sea'          , 'Poison Point' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (118, 'Goldeen'    , 'Water'   , NULL      , 'Goldfish'   , 'Water''s-edge', 'Water Veil'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (119, 'Seaking'    , 'Water'   , NULL      , 'Goldfish'   , 'Water''s-edge', 'Swift Swim'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (120, 'Staryu'     , 'Water'   , NULL      , 'Star Shape' , 'Sea'          , 'Natural Cure' , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (121, 'Starmine'   , 'Water'   , 'Psychic' , 'Mysterious' , 'Sea'          , 'Natural Cure' , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (122, 'Mr. Mime'   , 'Psychic' , NULL      , 'Barrier'    , 'Urban'        , 'Soundproof'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (123, 'Scyther'    , 'Bug'     , 'Flying'  , 'Mantis'     , 'Grassland'    , 'Swarm'        , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (124, 'Jynx'       , 'Ice'     , 'Psychic' , 'Human Shape', 'Urban'        , 'Oblivious'    , 0   , 100 , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (125, 'Electabuzz' , 'Electric', NULL      , 'Electric'   , 'Grassland'    , 'Static'       , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (126, 'Magmar'     , 'Fire'    , NULL      , 'Spitfire'   , 'Mountain'     , 'Flame Body'   , 75.0, 25.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (127, 'Pinsir'     , 'Bug'     , NULL      , 'Stag Beetle', 'Forest'       , 'Hyper Cutter' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (128, 'Tauros'     , 'Normal'  , NULL      , 'Wild Bull'  , 'Grassland'    , 'Intimidate'   , 100 , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (129, 'Magikarp'   , 'Water'   , NULL      , 'Fish'       , 'Water''s-edge', 'Swift Swim'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (130, 'Gyarados'   , 'Water'   , 'Flying'  , 'Atrocious'  , 'Water''s-edge', 'Intimidate'   , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (131, 'Lapras'     , 'Water'   , 'Ice'     , 'Transport'  , 'Sea'          , 'Water Absorb' , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (132, 'Ditto'      , 'Normal'  , NULL      , 'Transform'  , 'Urban'        , 'Limber'       , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (133, 'Eevee'      , 'Normal'  , NULL      , 'Evolution'  , 'Urban'        , 'Run Away'     , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (134, 'Vaporeon'   , 'Water'   , NULL      , 'Bubble Jet' , 'Urban'        , 'Water Absorb' , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (135, 'Jolteon'    , 'Electric', NULL      , 'Lightning'  , 'Urban'        , 'Volt Absorb'  , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (136, 'Flareon'    , 'Fire'    , NULL      , 'Flame'      , 'Urban'        , 'Flash Fire'   , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (137, 'Porygon'    , 'Normal'  , NULL      , 'Virtual'    , 'Urban'        , 'Trace'        , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (138, 'Omanyte'    , 'Rock'    , 'Water'   , 'Spiral'     , 'Sea'          , 'Shell Armor'  , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (139, 'Omastar'    , 'Rock'    , 'Water'   , 'Spiral'     , 'Sea'          , 'Swift Swim'   , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (140, 'Kabuto'     , 'Rock'    , 'Water'   , 'Shellfish'  , 'Sea'          , 'Battle Armor' , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (141, 'Kabutops'   , 'Rock'    , 'Water'   , 'Shellfish'  , 'Sea'          , 'Swift Swim'   , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (142, 'Aerodactyl' , 'Rock'    , 'Flying'  , 'Fossil'     , 'Mountain'     , 'Rock Head'    , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (143, 'Snorlax'    , 'Normal'  , NULL      , 'Sleeping'   , 'Mountain'     , 'Thick Fat'    , 87.5, 12.5, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (144, 'Articuno'   , 'Ice'     , 'Flying'  , 'Freeze'     , 'Rare'         , 'Pressure'     , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (145, 'Zapdos'     , 'Electric', 'Flying'  , 'Electric'   , 'Rare'         , 'Pressure'     , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (146, 'Moltres'    , 'Fire'    , 'Flying'  , 'Flame'      , 'Rare'         , 'Pressure'     , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (147, 'Dratini'    , 'Dragon'  , NULL      , 'Dragon'     , 'Water''s-edge', 'Shed Skin'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (148, 'Dragonair'  , 'Dragon'  , NULL      , 'Dragon'     , 'Water''s-edge', 'Shed Skin'    , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (149, 'Dragonite'  , 'Dragon'  , NULL      , 'Dragon'     , 'Water''s-edge', 'Inner Focus'  , 50.0, 50.0, 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (150, 'Mewtwo'     , 'Psychic' , NULL      , 'Genetic'    , 'Rare'         , 'Pressure'     , 0   , 0   , 0, 0);
INSERT INTO pokedex_kanto(NO, pokemon, type1, type2, classification, category, ability, male, female, height, weight) VALUES (151, 'Mew'        , 'Psychic' , NULl      , 'New Species', 'Rare'         , 'Synchronize'  , 0   , 0   , 0, 0);

CREATE TABLE movedex_gen3(
    name VARCHAR(14),
    type VARCHAR(8),
    category VARCHAR(8),
    power INT,
    accuracy INT,
    PP INT,
    effect VARCHAR(200)
);
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Aerial Ace'    , 'Flying'  , 'Physical', 60  , -1  , 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Air Cutter'    , 'Flying'  , 'Special' , 60  , 95  , 25, 'High critical hit ratio.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Arm Thrust'    , 'Fighting', 'Physical', 15  ,100  , 20, 'Hits 2-5 times in one turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Aromatherapy'  , 'Grass'   , 'Status'  , NULL, NULL, 5 , 'Cures all status   problems in your party.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Assist'        , 'Normal'  , 'Status'  , NULL, NULL, 20, 'User performs a move known by its allies at random.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Astonish'      , 'Ghost'   , 'Physical', 30  , 100 , 15, 'May cause flinching.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Blast Burn'    , 'Fire'    , 'Special' , 150 , 90  , 5 , 'User must recharge next turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Blaze Kick'    , 'Fire'    , 'Physical', 85  , 90  , 10, 'High critical hit ratio. May burn opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Block'         , 'Normal'  , 'Status'  , NULL, NULL, 5 , 'Opponent cannot flee or switch.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Bounce'        , 'Flying'  , 'Physical', 85  , 85  , 5 , 'Springs up on first turn, attacks on second. May paralyze opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Brick Break'   , 'Fighting', 'Physical', 75  , 100 , 15, 'Breaks through Reflect and Light Screen barriers.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Bulk Up'       , 'Fighting', 'Status'  , NULL, NULL, 20, 'Raises user''s Attack and Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Bullet Seed'   , 'Grass'   , 'Physical', 25  , 100 , 30, 'Hits 2-5 times in one turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Calm Mind'     , 'Psychic' , 'Status'  , NULL, NULL, 20, 'Raises user''s Special  Attack and Special  Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Camouflage'    , 'Normal'  , 'Status'  , NULL, NULL, 20, 'Changes user''s type according to the location.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Charge'        , 'Electric', 'Status'  , NULL, NULL, 20, 'Raises user''s Special  Defense and next Electric move''s power increases.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Cosmic Power'  , 'Psychic' , 'Status'  , NULL, NULL, 20, 'Raises user''s Defense and Special  Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Covet'         , 'Normal'  , 'Physical', 60  , 100 , 25, 'Opponent''s item is stolen by the user.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Crush Claw'    , 'Normal'  , 'Physical', 75  , 95  , 10, 'May lower opponent''s Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Dive'          , 'Water'   , 'Physical', 80  , 100 , 10, 'Dives underwater on first turn, attacks on second turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Doom Desire'   , 'Steel'   , 'Special' , 140 , 100 , 5 , 'Damage occurs 2 turns later.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Dragon Claw'   , 'Dragon'  , 'Physical', 80  , 100 , 15, NULL);
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Dragon Dance'  , 'Dragon'  , 'Status'  , NULL, NULL, 20, 'Raises user''s Attack and Speed.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Endeavor'      , 'Normal'  , 'Physical', NULL, 100 , 5 , 'Reduces opponent''s HP to same as user''s.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Eruption'      , 'Fire'    , 'Special' , 150 , 100 , 5 , 'Stronger when the user''s HP is higher.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Extrasensory'  , 'Psychic' , 'Special' , 80  , 100 , 20, 'May cause flinching.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Facade'        , 'Normal'  , 'Physical', 70  , 100 , 20, 'Power doubles if user is burned, poisoned, or paralyzed.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Fake Out'      , 'Normal'  , 'Physical', 40  , 100 , 10, 'User attacks first, foe flinches. Only usable on first turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Fake Tears'    , 'Dark'    , 'Status'  , NULL, 100 , 20, 'Sharply lowers opponent''s Special Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Feather Dance' , 'Flying'  , 'Status'  , NULL, 100 , 15, 'Sharply lowers opponent''s Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Flatter'       , 'Dark'    , 'Status'  , NULL, 100 , 15, 'Confuses opponent, but raises its Special Attack by two stages.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Focus Punch'   , 'Fighting', 'Physical', 150 , 100 , 20, 'If the user is hit before attacking, it flinches instead.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Follow Me'     , 'Normal'  , 'Status'  , NULL, NULL, 20, 'In Double Battle, the user takes all the attacks.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Frenzy Plant'  , 'Grass'   , 'Special' , 150 , 90  , 5 , 'User must recharge next turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Grass Whistle' , 'Grass'   , 'Status'  , NULL, 55  , 15, 'Puts opponent to sleep.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Growl'         , 'Normal'  , 'Status'  , NULL, 100 , 40, 'The user growls in a cute way, making the foe lower its Attacl stat.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Grudge'        , 'Ghost'   , 'Status'  , NULL, NULL, 5 , 'If the users faints after using this move, the PP for the opponent''s last move is depleted.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Hail'          , 'Ice'     , 'Status'  , NULL, NULL, 10, 'Non-Ice types are damaged for 5 turns.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Heat Wave'     , 'Fire'    , 'Special' , 95  , 90  , 10, 'May burn opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Helping Hand'  , 'Normal'  , 'Status'  , NULL, NULL, 20, 'In Double Battles, boosts the power of the partner''s move.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Howl'          , 'Normal'  , 'Status'  , NULL, NULL, 40, 'Raises user''s Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Hydro Cannon'  , 'Water'   , 'Special' , 150 , 90  , 5 , 'User must recharge next turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Hyper Voice'   , 'Normal'  , 'Special' , 90  , 100 , 10, NULL);
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Ice Ball'      , 'Ice'     , 'Physical', 30  , 90  , 20, 'Doubles in power each turn for 5 turns.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Icicle Spear'  , 'Ice'     , 'Physical', 25  , 100 , 30, 'Hits 2-5 times in one turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Imprison'      , 'Psychic' , 'Status'  , NULL, NULL, 10, 'Opponent is unable to use moves that the user also knows.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Ingrain'       , 'Grass'   , 'Status'  , NULL, NULL, 20, 'User restores HP each turn. User cannot escape/switch.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Iron Defense'  , 'Steel'   , 'Status'  , NULL, NULL, 15, 'Sharply raises user''s Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Knock Off'     , 'Dark'    , 'Physical', 65  , 100 , 20, 'Removes opponent''s held item for the rest of the battle.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Leaf Blade'    , 'Grass'   , 'Physical', 90  , 100 , 15, 'High critical hit ratio.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Luster Purge'  , 'Psychic' , 'Special' , 70  , 100 , 5 , 'May lower opponent''s Special  Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Magic Coat'    , 'Psychic' , 'Status'  , NULL, NULL, 15, 'Reflects moves that cause status   conditions back to the attacker.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Magical Leaf'  , 'Grass'   , 'Special' , 60  , -1  , 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Memento'       , 'Dark'    , 'Status'  , NULL, 100 , 10, 'User faints, sharply lowers opponent''s Attack and Special  Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Metal Sound'   , 'Steel'   , 'Status'  , NULL, 85  , 40, 'Sharply lowers opponent''s Special Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Meteor Mash'   , 'Steel'   , 'Physical', 90  , 90  , 10, 'May raise user''s Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Mist Ball'     , 'Psychic' , 'Special' , 70  , 100 , 5 , 'May lower opponent''s Special Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Mud Shot'      , 'Ground'  , 'Special' , 55  , 95  , 15, 'Lowers opponent''s Speed.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Mud Sport'     , 'Ground'  , 'Status'  , NULL, NULL, 15, 'Weakens the power of Electric-type moves.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Muddy Water'   , 'Water'   , 'Special' , 90  , 85  , 10, 'May lower opponent''s Accuracy.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Nature Power'  , 'Normal'  , 'Status'  , NULL, NULL, 20, 'Uses a certain move based on the current terrain.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Needle Arm'    , 'Grass'   , 'Physical', 60  , 100 , 15, 'May cause flinching.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Odor Sleuth'   , 'Normal'  , 'Status'  , NULL, NULL, 40, 'Resets opponent''s Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Overheat'      , 'Fire'    , 'Special' , 130 , 90  , 5 , 'Sharply lowers user''s Special  Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Poison Fang'   , 'Poison'  , 'Physical', 50  , 100 , 15, 'May badly poison opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Poison Tail'   , 'Poison'  , 'Physical', 50  , 100 , 25, 'High critical hit ratio. May poison opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Psycho Boost'  , 'Psychic' , 'Special' , 140 , 90  , 5 , 'Sharply lowers user''s Special  Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Recycle'       , 'Normal'  , 'Status'  , NULL, NULL, 10, 'User''s used hold item is restored.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Refresh'       , 'Normal'  , 'Status'  , NULL, NULL, 20, 'Cures paralysis, poison, and burns.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Revenge'       , 'Fighting', 'Physical', 60  , 100 , 10, 'Power increases if user was hit first.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Rock Blast'    , 'Rock'    , 'Physical', 25  , 90  , 10, 'Hits 2-5 times in one turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Rock Tomb'     , 'Rock'    , 'Physical', 60  , 95  , 15, 'Lowers opponent''s Speed.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Role Play'     , 'Psychic' , 'Status'  , NULL, NULL, 15, 'User copies the opponent''s Ability.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Sand Tomb'     , 'Ground'  , 'Physical', 35  , 85  , 15, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Scratch'       , 'Normal'  , 'Physical', 40  , 100 , 20, 'Hard, pointed, and sharp claws rake the foe.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Secret Power'  , 'Normal'  , 'Physical', 70  , 100 , 20, 'Effects of the attack vary with the location.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Shadow Punch'  , 'Ghost'   , 'Physical', 60  , -1  , 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Sheer Cold'    , 'Ice'     , 'Special' , NULL, NULL, 5 , 'One-Hit-KO, if it hits.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Shock Wave'    , 'Electric', 'Special' , 60  , -1  , 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Signal Beam'   , 'Bug'     , 'Special' , 75  , 100 , 15, 'May confuse opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Silver Wind'   , 'Bug'     , 'Special' , 60  , 100 , 5 , 'May raise all stats of user at once.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Skill Swap'    , 'Psychic' , 'Status'  , NULL, NULL, 10, 'The user swaps Abilities with the opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Sky Uppercut'  , 'Fighting', 'Physical', 85  , 90  , 15, 'Hits the opponent, even during Fly.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Slack Off'     , 'Normal'  , 'Status'  , NULL, NULL, 10, 'User recovers half its max HP.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Smelling Salts', 'Normal'  , 'Physical', 70  , 100 , 10, 'Power doubles if opponent is paralyzed, but cures it.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Snatch'        , 'Dark'    , 'Status'  , NULL, NULL, 10, 'Steals the effects of the opponent''s next move.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Spit Up'       , 'Normal'  , 'Special' , NULL, 100 , 10, 'Power depends on how many times the user performed Stockpile.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Stockpile'     , 'Normal'  , 'Status'  , NULL, NULL, 20, 'Stores energy for use with Spit Up and Swallow.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Superpower'    , 'Fighting', 'Physical', 120 , 100 , 5 , 'Lowers user''s Attack and Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Swallow'       , 'Normal'  , 'Status'  , NULL, NULL, 10, 'The more times the user has performed Stockpile, the more HP is recovered.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Tackle'        , 'Normal'  , 'Physical', 40  , 100 , 35, 'A physical attack in which the user charges, full body, into the foe.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Tail Glow'     , 'Bug'     , 'Status'  , NULL, NULL, 20, 'Drastically raises user''s Special  Attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Tail Whip'     , 'Normal'  , 'Status'  , NULL, 100 , 30, 'The user wags its tail cutely, making the foe lower its Defense stat.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Taunt'         , 'Dark'    , 'Status'  , NULL, 100 , 20, 'Opponent can only use moves that attack.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Teeter Dance'  , 'Normal'  , 'Status'  , NULL, 100 , 20, 'Confuses all PoNULL on.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Tickle'        , 'Normal'  , 'Status'  , NULL, 100 , 20, 'Lowers opponent''s Attack and Defense.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Torment'       , 'Dark'    , 'Status'  , NULL, 100 , 15, 'Opponent cannot use the same move in a row.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Trick'         , 'Psychic' , 'Status'  , NULL, 100 , 10, 'Swaps held items with the opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Uproar'        , 'Normal'  , 'Special' , 90  , 100 , 10, 'User attacks for 3 turns and prevents sleep.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Volt Tackle'   , 'Electric', 'Physical', 120 , 100 , 15, 'User receives recoil damage. May paralyze opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Water Pulse'   , 'Water'   , 'Special' , 60  , 100 , 20, 'May confuse opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Water Sport'   , 'Water'   , 'Status'  , NULL, NULL, 15, 'Weakens the power of Fire-type moves.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Water Spout'   , 'Water'   , 'Special' , 150 , 100 , 5 , 'The higher the user''s HP, the higher the damage caused.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Weather Ball'  , 'Normal'  , 'Special' , 50  , 100 , 10, 'Move''s power and type changes with the weather.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Will-O-Wisp'   , 'Fire'    , 'Status'  , NULL, 85  , 15, 'Burns opponent.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Wish'          , 'Normal'  , 'Status'  , NULL, NULL, 10, 'The user recovers HP in the following turn.');
INSERT INTO movedex_gen3(name, type, category, power, accuracy, PP, effect) VALUES('Yawn'          , 'Normal'  , 'Status'  , NULL, NULL, 10, 'Puts opponent to sleep in the next turn.');

CREATE TABLE squirtle_moves (
    move VARCHAR(14),
    level INT
);
INSERT INTO squirtle_moves(move, level) VALUES('Tackle'    , 1);
INSERT INTO squirtle_moves(move, level) VALUES('Tail Whip' , 4);
INSERT INTO squirtle_moves(move, level) VALUES('Bubble'    , 7);
INSERT INTO squirtle_moves(move, level) VALUES('Withdraw'  , 10);
INSERT INTO squirtle_moves(move, level) VALUES('Water Gun' , 13);
INSERT INTO squirtle_moves(move, level) VALUES('Bite'      , 18);
INSERT INTO squirtle_moves(move, level) VALUES('Rapid Spin', 23);
INSERT INTO squirtle_moves(move, level) VALUES('Protect'   , 28);
INSERT INTO squirtle_moves(move, level) VALUES('Rain Dance', 33);
INSERT INTO squirtle_moves(move, level) VALUES('Skull Bash', 40);
INSERT INTO squirtle_moves(move, level) VALUES('Hydro Pump', 47);

CREATE TABLE charmander_moves (
    move VARCHAR(14),
    level INT
);
INSERT INTO charmander_moves(move, level) VALUES('Growl'        , 1);
INSERT INTO charmander_moves(move, level) VALUES('Scratch'      , 1);
INSERT INTO charmander_moves(move, level) VALUES('Ember'        , 7);
INSERT INTO charmander_moves(move, level) VALUES('Metal Claw'   , 13);
INSERT INTO charmander_moves(move, level) VALUES('Smokescreen'  , 19);
INSERT INTO charmander_moves(move, level) VALUES('Scary Face'   , 25);
INSERT INTO charmander_moves(move, level) VALUES('Flamethrower' , 31);
INSERT INTO charmander_moves(move, level) VALUES('Slash'        , 37);
INSERT INTO charmander_moves(move, level) VALUES('Dragon Rage'  , 43);
INSERT INTO charmander_moves(move, level) VALUES('Fire Spin'    , 49);